namespace: dorfgefluester
deploymentMode: monolith

web:
  image:
    repository: dev-env-01:5000/dorfgefluester
    tag: master-latest
    pullPolicy: Always

api:
  image:
    repository: dev-env-01:5000/dorfgefluester-api
    tag: master-latest
    pullPolicy: Always
  env:
    appOrigin: http://dev-env-01

postgres:
  enabled: true
  auth:
    secretName: dorfgefluester-postgres

ingress:
  host: dev-env-01
  path: /dorfgefluester
  apiPath: /api
  tls:
    enabled: false
  stripPrefix:
    enabled: false
