{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dorfgefluester.postgresName" . }}
  labels:
    {{- include "dorfgefluester.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "dorfgefluester.postgresSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.containerPort }}
{{- end }}
