{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dorfgefluester.redisName" . }}
  labels:
    {{- include "dorfgefluester.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dorfgefluester.redisSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dorfgefluester.redisSelectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          args: ["redis-server", "--save", "", "--appendonly", "no"]
          ports:
            - containerPort: {{ .Values.redis.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.redis.resources.requests.cpu | quote }}
              memory: {{ .Values.redis.resources.requests.memory | quote }}
            limits:
              memory: {{ .Values.redis.resources.limits.memory | quote }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.redis.containerPort }}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.redis.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
{{- end }}
