{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dorfgefluester.redisName" . }}
  labels:
    {{- include "dorfgefluester.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "dorfgefluester.redisSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.containerPort }}
      protocol: TCP
      name: redis
{{- end }}
