{{- if ne .Values.deploymentMode "monolith" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dorfgefluester.webName" . }}
  labels:
    {{- include "dorfgefluester.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "dorfgefluester.webSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.containerPort }}
{{- end }}
